;;;; @(#)$Id: win32api.scm,v 1.2 1999/02/15 08:16:05 qfwfq Exp $

(rp:ww-load-system-dll kernel "kernel32.dll")

(rp:ww-book-api-entry get-version-ex kernel "GetVersionExA" integer (buffer))
(rp:ww-book-api-entry get-last-error kernel "GetLastError" cardinal ())
(rp:ww-book-api-entry format-message kernel "FormatMessageA" cardinal
  (cardinal buffer cardinal cardinal buffer cardinal buffer))
(rp:ww-book-api-entry global-free kernel "GlobalFree" buffer (buffer))
(rp:ww-book-api-entry local-free kernel "LocalFree" buffer (buffer))
(rp:ww-book-api-entry get-module-handle kernel "GetModuleHandleA" buffer (buffer))
(rp:ww-book-api-entry multi-byte-to-wide-char kernel "MultiByteToWideChar" integer
  (cardinal cardinal buffer integer buffer integer))
(rp:ww-book-api-entry create-file kernel "CreateFileA" buffer
  (buffer cardinal cardinal buffer cardinal cardinal buffer))
(rp:ww-book-api-entry close-handle kernel "CloseHandle" integer (buffer))
(rp:ww-book-api-entry write-file kernel "WriteFile" integer (buffer buffer cardinal buffer buffer))
(rp:ww-book-api-entry read-file kernel "ReadFile" integer (buffer buffer cardinal buffer buffer))

(rp:ww-load-system-dll user "user32.dll")

(rp:ww-book-api-entry register-class-ex user "RegisterClassExA" cardinal (buffer))
(rp:ww-book-api-entry get-class-info-ex user "GetClassInfoExA" integer (buffer buffer buffer))
(rp:ww-book-api-entry create-window-ex user "CreateWindowExA" buffer
  (cardinal buffer buffer cardinal integer integer integer integer buffer buffer buffer buffer))
(rp:ww-book-api-entry destroy-window user "DestroyWindow" integer (buffer))
(rp:ww-book-api-entry create-accelerator-table user "CreateAcceleratorTableA" buffer (buffer integer))
(rp:ww-book-api-entry destroy-accelerator-table user "DestroyAcceleratorTable" integer (buffer))
(rp:ww-book-api-entry get-message user "GetMessageA" integer (buffer buffer cardinal cardinal))
(rp:ww-book-api-entry peek-message user "PeekMessageA" integer (buffer buffer cardinal cardinal cardinal))
(rp:ww-book-api-entry wait-message user "WaitMessage" integer ())
(rp:ww-book-api-entry dispatch-message user "DispatchMessageA" integer (buffer))
(rp:ww-book-api-entry send-message user "SendMessageA" integer (buffer cardinal cardinal integer))
(rp:ww-book-api-entry post-message user "PostMessageA" integer (buffer cardinal cardinal integer))
(rp:ww-book-api-entry translate-message user "TranslateMessage" integer (buffer))
(rp:ww-book-api-entry translate-accelerator user "TranslateAcceleratorA" integer (buffer buffer buffer))
(rp:ww-book-api-entry is-dialog-message user "IsDialogMessageA" integer (buffer buffer))
(rp:ww-book-api-entry post-quit-message user "PostQuitMessage" effect (integer))
(rp:ww-book-api-entry call-window-proc user "CallWindowProcA" integer (procedure buffer cardinal cardinal integer))
(rp:ww-book-api-entry set-timer user "SetTimer" cardinal (buffer cardinal cardinal procedure))
(rp:ww-book-api-entry kill-timer user "KillTimer" integer (buffer cardinal))
(rp:ww-book-api-entry show-window user "ShowWindow" integer (buffer integer))
(rp:ww-book-api-entry set-window-pos user "SetWindowPos" integer
  (buffer buffer integer integer integer integer cardinal))
(rp:ww-book-api-entry enable-window user "EnableWindow" integer (buffer integer))
(rp:ww-book-api-entry update-window user "UpdateWindow" integer (buffer))
(rp:ww-book-api-entry get-parent user "GetParent" buffer (buffer))
(rp:ww-book-api-entry invalidate-rect user "InvalidateRect" integer (buffer buffer integer))
(rp:ww-book-api-entry set-window-text user "SetWindowTextA" integer (buffer buffer))
(rp:ww-book-api-entry set-class-long user "SetClassLongA" integer (buffer integer integer))
(rp:ww-book-api-entry get-class-long user "GetClassLongA" integer (buffer integer))
(rp:ww-book-api-entry set-window-long user "SetWindowLongA" integer (buffer integer integer))
(rp:ww-book-api-entry get-window-long user "GetWindowLongA" integer (buffer integer))
(rp:ww-book-api-entry def-window-proc user "DefWindowProcA" integer (buffer cardinal cardinal integer))
(rp:ww-book-api-entry begin-paint user "BeginPaint" buffer (buffer buffer))
(rp:ww-book-api-entry end-paint user "EndPaint" integer (buffer buffer))
(rp:ww-book-api-entry get-dc user "GetDC" buffer (buffer))
(rp:ww-book-api-entry release-dc user "ReleaseDC" integer (buffer buffer))
(rp:ww-book-api-entry get-client-rect user "GetClientRect" integer (buffer buffer))
(rp:ww-book-api-entry load-icon user "LoadIconA" buffer (buffer buffer))
(rp:ww-book-api-entry load-cursor user "LoadCursorA" buffer (buffer buffer))
(rp:ww-book-api-entry set-cursor user "SetCursor" buffer (buffer))
(rp:ww-book-api-entry get-system-menu user "GetSystemMenu" buffer (buffer integer))
(rp:ww-book-api-entry create-menu user "CreateMenu" buffer ())
(rp:ww-book-api-entry insert-menu-item user "InsertMenuItemA" integer (buffer cardinal integer buffer))
(rp:ww-book-api-entry enable-menu-item user "EnableMenuItem" integer (buffer cardinal cardinal))
(rp:ww-book-api-entry check-menu-item user "CheckMenuItem" cardinal (buffer cardinal cardinal))
(rp:ww-book-api-entry show-scroll-bar user "ShowScrollBar" integer (buffer integer integer))
(rp:ww-book-api-entry enable-scroll-bar user "EnableScrollBar" integer (buffer cardinal cardinal))
(rp:ww-book-api-entry set-scroll-info user "SetScrollInfo" integer (buffer integer buffer integer))
(rp:ww-book-api-entry get-scroll-info user "GetScrollInfo" integer (buffer integer buffer))
(rp:ww-book-api-entry create-dialog-indirect-param user "CreateDialogIndirectParamA" buffer
  (buffer buffer buffer procedure integer))
(rp:ww-book-api-entry dialog-box-indirect-param user "DialogBoxIndirectParamA" integer
  (buffer buffer buffer procedure integer))
(rp:ww-book-api-entry end-dialog user "EndDialog" integer (buffer integer))
(rp:ww-book-api-entry get-dlg-item user "GetDlgItem" buffer (buffer integer))
(rp:ww-book-api-entry send-dlg-item-message user "SendDlgItemMessageA" integer
  (buffer integer cardinal cardinal integer))
(rp:ww-book-api-entry message-box user "MessageBoxA" integer (buffer buffer buffer cardinal))
(rp:ww-book-api-entry message-beep user "MessageBeep" integer (cardinal))
(rp:ww-book-api-entry invert-rect user "InvertRect" integer (buffer buffer))
(rp:ww-book-api-entry draw-focus-rect user "DrawFocusRect" integer (buffer buffer))
(rp:ww-book-api-entry draw-text user "DrawTextA" integer (buffer buffer integer buffer cardinal))
(rp:ww-book-api-entry scroll-window-ex user "ScrollWindowEx" integer
  (buffer integer integer buffer buffer buffer buffer cardinal))
(rp:ww-book-api-entry client-to-screen user "ClientToScreen" integer (buffer buffer))
(rp:ww-book-api-entry screen-to-client user "ScreenToClient" integer (buffer buffer))
(rp:ww-book-api-entry drag-detect user "DragDetect" integer (buffer integer integer))
(rp:ww-book-api-entry set-capture user "SetCapture" buffer (buffer))
(rp:ww-book-api-entry release-capture user "ReleaseCapture" integer ())
(rp:ww-book-api-entry set-focus user "SetFocus" buffer (buffer))
(rp:ww-book-api-entry get-focus user "GetFocus" buffer ())
(rp:ww-book-api-entry get-key-state user "GetKeyState" integer (integer))

(rp:ww-load-system-dll gdi "gdi32.dll")

(rp:ww-book-api-entry set-abort-proc gdi "SetAbortProc" integer (buffer procedure))
(rp:ww-book-api-entry delete-dc gdi "DeleteDC" integer (buffer))
(rp:ww-book-api-entry start-doc gdi "StartDocA" integer (buffer buffer))
(rp:ww-book-api-entry end-doc gdi "EndDoc" integer (buffer))
(rp:ww-book-api-entry abort-doc gdi "AbortDoc" integer (buffer))
(rp:ww-book-api-entry start-page gdi "StartPage" integer (buffer))
(rp:ww-book-api-entry end-page gdi "EndPage" integer (buffer))
(rp:ww-book-api-entry rect-visible gdi "RectVisible" integer (buffer buffer))
(rp:ww-book-api-entry text-out gdi "TextOutA" integer (buffer integer integer buffer integer))
(rp:ww-book-api-entry move-to-ex gdi "MoveToEx" integer (buffer integer integer buffer))
(rp:ww-book-api-entry line-to gdi "LineTo" integer (buffer integer integer))
(rp:ww-book-api-entry rectangle gdi "Rectangle" integer (buffer integer integer integer integer))
(rp:ww-book-api-entry set-map-mode gdi "SetMapMode" integer (buffer integer))
(rp:ww-book-api-entry set-viewport-ext-ex gdi "SetViewportExtEx" integer (buffer integer integer buffer))
(rp:ww-book-api-entry set-viewport-org-ex gdi "SetViewportOrgEx" integer (buffer integer integer buffer))
(rp:ww-book-api-entry set-window-ext-ex gdi "SetWindowExtEx" integer (buffer integer integer buffer))
(rp:ww-book-api-entry set-window-org-ex gdi "SetWindowOrgEx" integer (buffer integer integer buffer))
(rp:ww-book-api-entry set-bk-mode gdi "SetBkMode" integer (buffer integer))
(rp:ww-book-api-entry set-text-align gdi "SetTextAlign" cardinal (buffer cardinal))
(rp:ww-book-api-entry select-object gdi "SelectObject" buffer (buffer buffer))
(rp:ww-book-api-entry get-stock-object gdi "GetStockObject" buffer (integer))
(rp:ww-book-api-entry create-pen gdi "CreatePen" buffer (integer integer cardinal))
(rp:ww-book-api-entry create-solid-brush gdi "CreateSolidBrush" buffer (cardinal))
(rp:ww-book-api-entry delete-object gdi "DeleteObject" integer (buffer))
(rp:ww-book-api-entry dp-to-lp gdi "DPtoLP" integer (buffer buffer integer))
(rp:ww-book-api-entry get-device-caps gdi "GetDeviceCaps" integer (buffer integer))
(rp:ww-book-api-entry get-text-metrics gdi "GetTextMetricsA" integer (buffer buffer))

(rp:ww-load-system-dll comdlg "comdlg32.dll")

(rp:ww-book-api-entry comm-dlg-extended-error comdlg "CommDlgExtendedError" cardinal ())
(rp:ww-book-api-entry get-open-file-name comdlg "GetOpenFileNameA" integer (buffer))
(rp:ww-book-api-entry get-save-file-name comdlg "GetSaveFileNameA" integer (buffer))
(rp:ww-book-api-entry page-setup-dlg comdlg "PageSetupDlgA" integer (buffer))
(rp:ww-book-api-entry print-dlg comdlg "PrintDlgA" integer (buffer))
