;;;; @(#)$Id: w_base.scm,v 1.1 1998/07/31 11:35:06 qfwfq Exp $

(rp:declare-flag-set win:	; constants with no prefix
  (white-brush 0)	; stock objects
  (ltgray-brush 1)
  (gray-brush 2)
  (dkgray-brush 3)
  (black-brush 4)
  (null-brush 5)
  (hollow-brush 5)
  (white-pen 6)
  (black-pen 7)
  (null-pen 8)
  (oem-fixed-font 10)
  (ansi-fixed-font 11)
  (ansi-var-font 12)
  (system-font 13)
  (device-default-font 14)
  (default-palette 15)
  (system-fixed-font 16)
  (default-gui-font 17)
  (dc-brush 18)
  (dc-pen 19)
  (stock-last 19)
  (transparent 1)	; background modes
  (opaque 2)
  (bkmode-last 2)
  (fvirtkey #x1)	; accelerator key flags
  (fnoinvert #x2)
  (fshift #x4)
  (fcontrol #x8)
  (falt #x10)
  (idok 1)		; dialog commands
  (idcancel 2)
  (idabort 3)
  (idretry 4)
  (idignore 5)
  (idyes 6)
  (idno 7)
  (idclose 8)
  (idhelp 9)
  (hterror -2)		; WM_NCHITTEST position code
  (httransparent -1)
  (htnowhere 0)
  (htclient 1)
  (htcaption 2)
  (htsysmenu 3)
  (htgrowbox 4)
  (htsize 4)
  (htmenu 5)
  (hthscroll 6)
  (htvscroll 7)
  (htminbutton 8)
  (htmaxbutton 9)
  (htleft 10)
  (htright 11)
  (httop 12)
  (httopleft 13)
  (httopright 14)
  (htbottom 15)
  (htbottomleft 16)
  (htbottomright 17)
  (htborder 18)
  (htreduce 8)
  (htzoom 9)
  (htsizefirst 10)
  (htsizelast 17)
  (htobject 19)
  (htclose 20)
  (hthelp 21)
  (driverversion 0)	; GetDeviceCaps index
  (technology 2)
  (horzsize 4)
  (vertsize 6)
  (horzres 8)
  (vertres 10)
  (bitspixel 12)
  (planes 14)
  (numbrushes 16)
  (numpens 18)
  (nummarkers 20)
  (numfonts 22)
  (numcolors 24)
  (pdevicesize 26)
  (curvecaps 28)
  (linecaps 30)
  (polygonalcaps 32)
  (textcaps 34)
  (clipcaps 36)
  (rastercaps 38)
  (aspectx 40)
  (aspecty 42)
  (aspectxy 44)
  (shadeblendcaps 45)
  (logpixelsx 88)
  (logpixelsy 90)
  (sizepalette 104)
  (numreserved 106)
  (colorres 108)
  (physicalwidth 110)
  (physicalheight 111)
  (physicaloffsetx 112)
  (physicaloffsety 113)
  (scalingfactorx 114)
  (scalingfactory 115)
  (vrefresh 116)
  (desktopvertres 117)
  (desktophorzres 118)
  (bltalignment 119))

(rp:declare-constants win:gwl	; GetWindowLong offsets
  (wndproc -4)
  (hinstance -6)
  (hwndparent -8)
  (style -16)
  (exstyle -20)
  (userdata -21)
  (id -12))

(rp:define-buffer-structure win:point
  (x integer)
  (y integer))

(rp:define-buffer-structure win:size
  (cx integer)
  (cy integer))

(rp:define-buffer-structure win:rect
  (left integer)
  (top integer)
  (right integer)
  (bottom integer))

(rp:define-buffer-structure win:createstruct
  (create-params buffer)
  (instance buffer)
  (menu buffer)
  (wnd-parent buffer)
  (cy integer)
  (cx integer)
  (y integer)
  (x integer)
  (style integer)
  (name buffer)
  (class buffer)
  (ex-style cardinal))
