;;;; @(#)$Id: w_c_btn.scm,v 1.1 1998/07/31 11:35:06 qfwfq Exp $

(rp:declare-flag-set win:bs	; button style
  (pushbutton #x0)
  (defpushbutton #x1)
  (checkbox #x2)
  (autocheckbox #x3)
  (radiobutton #x4)
  (three-state #x5)
  (auto3state #x6)
  (groupbox #x7)
  (userbutton #x8)
  (autoradiobutton #x9)
  (ownerdraw #xb)
  (lefttext #x20)
  (text #x0)
  (icon #x40)
  (bitmap #x80)
  (left #x100)
  (right #x200)
  (center #x300)
  (top #x400)
  (bottom #x800)
  (vcenter #xc00)
  (pushlike #x1000)
  (multiline #x2000)
  (notify #x4000)
  (flat #x8000)
  (rightbutton #x20))

(rp:declare-constants win:bm	; Button messages
  (getcheck #xf0)
  (setcheck #xf1)
  (getstate #xf2)
  (setstate #xf3)
  (setstyle #xf4)
  (click #xf5)
  (getimage #xf6)
  (setimage #xf7))

(rp:declare-constants win:bn	; Button notification
  (clicked 0)
  (paint 1)
  (hilite 2)
  (unhilite 3)
  (disable 4)
  (doubleclicked 5)
  (pushed 2)
  (unpushed 3)
  (dblclk 5)
  (setfocus 6)
  (killfocus 7))

(rp:declare-flag-set win:bst	; Button status
  (unchecked #x0)
  (checked #x1)
  (indeterminate #x2)
  (pushed #x4)
  (focus #x8))
