;;;; @(#)$Id: w_class.scm,v 1.1 1998/07/31 11:35:08 qfwfq Exp $

(rp:declare-flag-set win:cs	; WNDCLASSEX style
  (vredraw #x1)
  (hredraw #x2)
  (dblclks #x8)
  (owndc #x20)
  (classdc #x40)
  (parentdc #x80)
  (noclose #x200)
  (savebits #x800)
  (bytealignclient #x1000)
  (bytealignwindow #x2000)
  (globalclass #x4000)
  (ime #x10000))

(rp:define-buffer-structure (win:wndclassex style proc mname cname)
  (size cardinal (win:wndclassex-size))
  (style cardinal style)
  (wnd-proc procedure proc)
  (cls-extra integer 0)
  (wnd-extra integer 0)
  (instance buffer (rp:win32api-get-module-handle #f))
  (icon buffer (rp:win32api-load-icon #f (rp:cast-integer->buffer (win:idi application))))
  (cursor buffer (rp:win32api-load-cursor #f (rp:cast-integer->buffer (win:idc arrow))))
  (background buffer (rp:cast-integer->buffer (rp:+ 1 (win:color window))))
  (menu-name buffer mname)
  (class-name buffer (rp:export-string cname))
  (icon-sm buffer #f))
