;;;; @(#)$Id: w_dc.scm,v 1.1 1998/07/31 11:35:08 qfwfq Exp $

(rp:declare-constants win:mm	; Mapping Modes
  (text 1)
  (lometric 2)
  (himetric 3)
  (loenglish 4)
  (hienglish 5)
  (twips 6)
  (isotropic 7)
  (anisotropic 8)
  (min 1)
  (max 8)
  (max-fixedscale 6))

(rp:declare-flag-set win:ta	; text alignment
  (noupdatecp 0)
  (updatecp 1)
  (left 0)
  (right 2)
  (center 6)
  (top 0)
  (bottom 8)
  (baseline 24)
  (rtlreading 256)
  (mask 287))

(rp:declare-flag-set win:ps	; Pen Styles
  (solid 0)
  (dash 1)
  (dot 2)
  (dashdot 3)
  (dashdotdot 4)
  (null 5)
  (insideframe 6)
  (userstyle 7)
  (alternate 8)
  (style-mask #xf)
  (endcap-round #x0)
  (endcap-square #x100)
  (endcap-flat #x200)
  (endcap-mask #xf00)
  (join-round #x0)
  (join-bevel #x1000)
  (join-miter #x2000)
  (join-mask #xf000)
  (cosmetic #x0)
  (geometric #x10000)
  (type-mask #xf0000))

(rp:define-buffer-structure win:paintstruct
  (dc buffer)
  (erase integer)
  (paint structure win:rect)
  (restore integer)
  (inc-update integer)
  (rgb-reserved byte-array 32))

(rp:define-buffer-structure (win:docinfo name)
  (size integer (win:docinfo-size))
  (doc-name buffer (rp:export-string name))
  (output buffer #f)
  (datatype buffer #f)
  (type cardinal 0))

(rp:define-buffer-structure win:textmetric
  (tm-height integer)
  (tm-ascent integer)
  (tm-descent integer)
  (tm-internal-leading integer)
  (tm-external-leading integer)
  (tm-ave-char-width integer)
  (tm-max-char-width integer)
  (tm-weight integer)
  (tm-overhang integer)
  (tm-digitized-aspect-x integer)
  (tm-digitized-aspect-y integer)
  (tm-first-char byte-array 1)
  (tm-last-char byte-array 1)
  (tm-default-char byte-array 1)
  (tm-break-char byte-array 1)
  (tm-italic byte-array 1)
  (tm-underlined byte-array 1)
  (tm-struck-out byte-array 1)
  (tm-pitch-and-family byte-array 1)
  (tm-char-set byte-array 1))
