;;;; @(#)$Id: w_dlg_pr.scm,v 1.2 1999/06/15 07:24:30 qfwfq Exp $

(rp:declare-flag-set win:pd	; PRINTDLG flags
  (allpages #x0)
  (selection #x1)
  (pagenums #x2)
  (noselection #x4)
  (nopagenums #x8)
  (collate #x10)
  (printtofile #x20)
  (printsetup #x40)
  (nowarning #x80)
  (returndc #x100)
  (returnic #x200)
  (returndefault #x400)
  (showhelp #x800)
  (enableprinthook #x1000)
  (enablesetuphook #x2000)
  (enableprinttemplate #x4000)
  (enablesetuptemplate #x8000)
  (enableprinttemplatehandle #x10000)
  (enablesetuptemplatehandle #x20000)
  (usedevmodecopies #x40000)
  (usedevmodecopiesandcollate #x40000)
  (disableprinttofile #x80000)
  (hideprinttofile #x100000)
  (nonetworkbutton #x200000))

(rp:define-packed-buffer-structure win:printdlg
  (struct-size cardinal (win:printdlg-size))
  (owner buffer)
  (dev-mode buffer)
  (dev-names buffer)
  (dc buffer)
  (flags cardinal)
  (from-page short-cardinal)
  (to-page short-cardinal)
  (min-page short-cardinal)
  (max-page short-cardinal)
  (copies short-cardinal)
  (instance buffer)
  (cust-data integer)
  (print-hook procedure)
  (setup-hook procedure)
  (print-template-name buffer)
  (setup-template-name buffer)
  (print-template buffer)
  (setup-template buffer))
