;;;; @(#)$Id: w_dlg_ps.scm,v 1.1 1998/07/31 11:35:11 qfwfq Exp $

(rp:declare-flag-set win:psd	; PAGESETUPDLG flags
  (defaultminmargins #x0)
  (inwininiintlmeasure #x0)
  (minmargins #x1)
  (margins #x2)
  (inthousandthsofinches #x4)
  (inhundredthsofmillimeters #x8)
  (disablemargins #x10)
  (disableprinter #x20)
  (nowarning #x80)
  (disableorientation #x100)
  (returndefault #x400)
  (disablepaper #x200)
  (showhelp #x800)
  (enablepagesetuphook #x2000)
  (enablepagesetuptemplate #x8000)
  (enablepagesetuptemplatehandle #x20000)
  (enablepagepainthook #x40000)
  (disablepagepainting #x80000)
  (nonetworkbutton #x200000))

(rp:define-buffer-structure win:pagesetupdlg
  (struct-size cardinal (win:pagesetupdlg-size))
  (owner buffer)
  (dev-mode buffer)
  (dev-names buffer)
  (flags cardinal)
  (paper-size structure win:point)
  (min-margin structure win:rect)
  (margin structure win:rect)
  (instance buffer)
  (cust-data integer)
  (page-setup-hook procedure)
  (page-paint-hook procedure)
  (page-setup-template-name buffer)
  (page-setup-template buffer))
