;;;; @(#)$Id: w_dlg_fl.scm,v 1.1 1998/07/31 11:35:09 qfwfq Exp $

(rp:declare-flag-set win:ofn	; OPENFILENAME flags
  (readonly #x1)
  (overwriteprompt #x2)
  (hidereadonly #x4)
  (nochangedir #x8)
  (showhelp #x10)
  (enablehook #x20)
  (enabletemplate #x40)
  (enabletemplatehandle #x80)
  (novalidate #x100)
  (allowmultiselect #x200)
  (extensiondifferent #x400)
  (pathmustexist #x800)
  (filemustexist #x1000)
  (createprompt #x2000)
  (shareaware #x4000)
  (noreadonlyreturn #x8000)
  (notestfilecreate #x10000)
  (nonetworkbutton #x20000)
  (nolongnames #x40000)
  (explorer #x80000)
  (nodereferencelinks #x100000)
  (longnames #x200000)
  (enableincludenotify #x400000)
  (enablesizing #x800000))

(rp:define-buffer-structure win:openfilename
  (struct-size cardinal (win:openfilename-size))
  (owner buffer)
  (instance buffer)
  (filter buffer)
  (custom-filter buffer)
  (max-cust-filter cardinal)
  (filter-index cardinal)
  (file buffer)
  (max-file cardinal)
  (file-title buffer)
  (max-file-title cardinal)
  (initial-dir buffer)
  (title buffer)
  (flags cardinal)
  (file-offset short-cardinal)
  (file-extension short-cardinal)
  (def-ext buffer)
  (cust-data integer)
  (hook procedure)
  (template-name buffer))
